//
//  SwiftAudioExPlaybackTests.swift
//  BriefeedTests
//
//  TDD Tests for SwiftAudioEx Playback of TTS Files
//  Written BEFORE implementation - these tests should fail initially
//

import XCTest
import AVFoundation
import MediaPlayer
@testable import Briefeed
// @testable import SwiftAudioEx // Will be imported when package is added

class SwiftAudioExPlaybackTests: XCTestCase {
    
    var audioPlayer: SwiftAudioExService!
    var unifiedPlayer: UnifiedAudioPlayer!
    var ttsService: TTSGeneratorService!
    
    override func setUp() {
        super.setUp()
        
        audioPlayer = SwiftAudioExService()
        unifiedPlayer = UnifiedAudioPlayer()
        ttsService = TTSGeneratorService()
    }
    
    override func tearDown() {
        audioPlayer?.stop()
        audioPlayer = nil
        unifiedPlayer = nil
        ttsService = nil
        super.tearDown()
    }
    
    // MARK: - Test 1: Play TTS-Generated Audio File
    
    func testPlayTTSGeneratedAudioFile() async throws {
        // Given: A TTS-generated audio file
        let text = "This audio was generated by TTS and should play in SwiftAudioEx"
        let audioURL = try await ttsService.generateAudioFile(from: text)
        
        // When: Playing with SwiftAudioEx
        try await audioPlayer.play(url: audioURL)
        
        // Then: Should be playing
        XCTAssertTrue(audioPlayer.isPlaying, "Audio should be playing")
        XCTAssertEqual(audioPlayer.state, SwiftAudioPlayerState.playing)
        XCTAssertGreaterThan(audioPlayer.duration, 0, "Should have valid duration")
    }
    
    // MARK: - Test 2: Speed Control Beyond TTS Limits
    
    func testSpeedControlBeyondTTSLimits() async throws {
        // Given: Playing audio
        let audioURL = try await generateTestAudio()
        try await audioPlayer.play(url: audioURL)
        
        // When: Setting speeds beyond TTS limits (> 2x)
        let speeds: [Float] = [0.5, 1.0, 2.0, 4.0, 8.0, 16.0, 20.0]
        
        for speed in speeds {
            audioPlayer.setRate(speed)
            
            // Then: Speed should be applied
            XCTAssertEqual(audioPlayer.rate, speed, accuracy: 0.01,
                          "Should support \(speed)x speed")
            
            // Wait briefly for rate to apply
            try await Task.sleep(nanoseconds: 100_000_000) // 0.1 second
            
            // Verify still playing at new rate
            XCTAssertTrue(audioPlayer.isPlaying,
                         "Should continue playing at \(speed)x")
        }
    }
    
    // MARK: - Test 3: Seeking in TTS Audio
    
    func testSeekingInTTSAudio() async throws {
        // Given: Playing TTS audio with known duration
        let audioURL = try await generateTestAudio()
        try await audioPlayer.play(url: audioURL)
        
        let duration = audioPlayer.duration
        XCTAssertGreaterThan(duration, 5.0, "Need at least 5 seconds for seek test")
        
        // When: Seeking to various positions
        let seekPositions = [0.0, duration * 0.25, duration * 0.5, duration * 0.75]
        
        for position in seekPositions {
            audioPlayer.seek(to: position)
            
            // Wait for seek to complete
            try await Task.sleep(nanoseconds: 200_000_000) // 0.2 seconds
            
            // Then: Current time should update
            XCTAssertEqual(audioPlayer.currentTime, position, accuracy: 0.5,
                          "Should seek to \(position) seconds")
            
            // And: Should continue playing from new position
            XCTAssertTrue(audioPlayer.isPlaying, "Should continue playing after seek")
        }
    }
    
    // MARK: - Test 4: Queue Transition with TTS Files
    
    func testQueueTransitionWithTTSFiles() async throws {
        // Given: Queue with multiple TTS-generated files
        let texts = [
            "First article about Swift",
            "Second article about iOS",
            "Third article about SwiftUI"
        ]
        
        var audioURLs: [URL] = []
        for text in texts {
            let url = try await ttsService.generateAudioFile(from: text)
            audioURLs.append(url)
        }
        
        // When: Loading queue
        try await audioPlayer.loadQueue(audioURLs)
        
        // Play first item
        try await audioPlayer.play(url: audioURLs[0])
        XCTAssertTrue(audioPlayer.isPlaying)
        
        // When: Moving to next
        audioPlayer.playNext()
        try await Task.sleep(nanoseconds: 500_000_000) // 0.5 seconds
        
        // Then: Should play next item
        XCTAssertTrue(audioPlayer.isPlaying, "Should play next item")
        
        // When: Moving to previous
        audioPlayer.playPrevious()
        try await Task.sleep(nanoseconds: 500_000_000) // 0.5 seconds
        
        // Then: Should play previous item
        XCTAssertTrue(audioPlayer.isPlaying, "Should play previous item")
    }
    
    // MARK: - Test 5: Article Playback Flow
    
    func testArticlePlaybackFlow() async throws {
        // Given: An article
        let article = createTestArticle(
            title: "Test Article",
            content: "This is a comprehensive test article about SwiftAudioEx integration."
        )
        
        // When: Playing article (TTS generation + playback)
        try await unifiedPlayer.play(article: article)
        
        // Then: Should generate TTS and play
        XCTAssertTrue(unifiedPlayer.isPlaying, "Should be playing")
        XCTAssertEqual(unifiedPlayer.currentTitle, "Test Article")
        XCTAssertNotNil(unifiedPlayer.currentAudioURL, "Should have audio URL")
        XCTAssertFalse(unifiedPlayer.isStreaming, "TTS audio is not streaming")
        XCTAssertGreaterThan(unifiedPlayer.duration, 0, "Should have duration")
    }
    
    // MARK: - Test 6: Pause and Resume
    
    func testPauseAndResume() async throws {
        // Given: Playing audio
        let audioURL = try await generateTestAudio()
        try await audioPlayer.play(url: audioURL)
        XCTAssertTrue(audioPlayer.isPlaying)
        
        let timeBeforePause = audioPlayer.currentTime
        
        // When: Pausing
        audioPlayer.pause()
        
        // Then: Should be paused
        XCTAssertFalse(audioPlayer.isPlaying)
        XCTAssertEqual(audioPlayer.state, SwiftAudioPlayerState.paused)
        
        // Wait a bit
        try await Task.sleep(nanoseconds: 1_000_000_000) // 1 second
        
        // Time should not advance while paused
        XCTAssertEqual(audioPlayer.currentTime, timeBeforePause, accuracy: 0.1)
        
        // When: Resuming
        audioPlayer.resume()
        
        // Then: Should resume playing
        XCTAssertTrue(audioPlayer.isPlaying)
        XCTAssertEqual(audioPlayer.state, SwiftAudioPlayerState.playing)
        
        // Wait and verify time advances
        try await Task.sleep(nanoseconds: 1_000_000_000) // 1 second
        XCTAssertGreaterThan(audioPlayer.currentTime, timeBeforePause)
    }
    
    // MARK: - Test 7: Background Playback
    
    func testBackgroundPlayback() async throws {
        // Given: Playing TTS audio
        let audioURL = try await generateTestAudio()
        try await audioPlayer.play(url: audioURL)
        XCTAssertTrue(audioPlayer.isPlaying)
        
        // When: App goes to background
        NotificationCenter.default.post(
            name: UIApplication.didEnterBackgroundNotification,
            object: nil
        )
        
        // Wait briefly
        try await Task.sleep(nanoseconds: 500_000_000) // 0.5 seconds
        
        // Then: Should continue playing
        XCTAssertTrue(audioPlayer.isPlaying,
                     "Should continue playing in background")
        XCTAssertTrue(audioPlayer.backgroundPlaybackEnabled,
                     "Background playback should be enabled")
    }
    
    // MARK: - Test 8: Now Playing Info
    
    func testNowPlayingInfo() async throws {
        // Given: An article being played
        let article = createTestArticle(
            title: "SwiftAudioEx Integration",
            content: "Testing Now Playing info with TTS audio"
        )
        
        // When: Playing article
        try await unifiedPlayer.play(article: article)
        
        // Wait for Now Playing to update
        try await Task.sleep(nanoseconds: 500_000_000) // 0.5 seconds
        
        // Then: Now Playing info should be set
        let nowPlaying = MPNowPlayingInfoCenter.default().nowPlayingInfo
        XCTAssertNotNil(nowPlaying, "Now Playing info should be set")
        XCTAssertEqual(nowPlaying?[MPMediaItemPropertyTitle] as? String,
                      "SwiftAudioEx Integration")
        XCTAssertNotNil(nowPlaying?[MPNowPlayingInfoPropertyElapsedPlaybackTime])
        XCTAssertNotNil(nowPlaying?[MPMediaItemPropertyPlaybackDuration])
        XCTAssertEqual(nowPlaying?[MPNowPlayingInfoPropertyPlaybackRate] as? Float,
                      unifiedPlayer.rate)
    }
    
    // MARK: - Test 9: Remote Control Commands
    
    func testRemoteControlCommands() async throws {
        // Given: Playing audio
        let audioURL = try await generateTestAudio()
        try await audioPlayer.play(url: audioURL)
        
        let commandCenter = MPRemoteCommandCenter.shared()
        
        // Test play/pause
        var event = MPRemoteCommandEvent()
        
        // When: Pause command
        _ = commandCenter.pauseCommand.target?(event)
        
        // Then: Should pause
        XCTAssertFalse(audioPlayer.isPlaying, "Should pause via remote command")
        
        // When: Play command
        _ = commandCenter.playCommand.target?(event)
        
        // Then: Should play
        XCTAssertTrue(audioPlayer.isPlaying, "Should play via remote command")
        
        // Test skip forward (30 seconds)
        let timeBefore = audioPlayer.currentTime
        _ = commandCenter.skipForwardCommand.target?(event)
        
        // Then: Should skip forward
        XCTAssertGreaterThan(audioPlayer.currentTime, timeBefore,
                            "Should skip forward")
    }
    
    // MARK: - Test 10: Progress Updates
    
    func testProgressUpdates() async throws {
        // Given: Delegate to track progress
        let expectation = XCTestExpectation(description: "Progress updates received")
        var progressUpdates: [Float] = []
        
        class TestDelegate: SwiftAudioExServiceDelegate {
            var onProgress: ((Float) -> Void)?
            
            func audioStateChanged(to newState: SwiftAudioPlayerState, from oldState: SwiftAudioPlayerState) {}
            func audioProgressUpdated(progress: Float, currentTime: TimeInterval, duration: TimeInterval) {
                onProgress?(progress)
            }
            func audioRateChanged(to rate: Float) {}
            func audioDidFinishPlaying(successfully: Bool) {}
        }
        
        let delegate = TestDelegate()
        delegate.onProgress = { progress in
            progressUpdates.append(progress)
            if progressUpdates.count >= 5 {
                expectation.fulfill()
            }
        }
        
        audioPlayer.delegate = delegate
        
        // When: Playing audio
        let audioURL = try await generateTestAudio()
        try await audioPlayer.play(url: audioURL)
        
        // Then: Should receive progress updates
        await fulfillment(of: [expectation], timeout: 10.0)
        
        XCTAssertGreaterThanOrEqual(progressUpdates.count, 5,
                                   "Should receive multiple progress updates")
        
        // Progress should increase
        for i in 1..<progressUpdates.count {
            XCTAssertGreaterThanOrEqual(progressUpdates[i], progressUpdates[i-1],
                                       "Progress should increase or stay same")
        }
    }
    
    // MARK: - Test 11: Memory Management
    
    func testMemoryManagementWithMultipleTTSFiles() async throws {
        // Given: Multiple TTS files played sequentially
        let texts = (1...10).map { "Test article number \($0) with some content." }
        
        for text in texts {
            // Generate and play
            let url = try await ttsService.generateAudioFile(from: text)
            try await audioPlayer.play(url: url)
            
            // Play briefly
            try await Task.sleep(nanoseconds: 200_000_000) // 0.2 seconds
            
            // Stop before next
            audioPlayer.stop()
        }
        
        // Then: Should not have memory leaks
        // Cache should be reasonable size
        let cacheSize = ttsService.cacheSize
        XCTAssertLessThan(cacheSize, 100 * 1024 * 1024, // 100MB
                         "Cache should not grow excessively")
    }
    
    // MARK: - Test 12: Error Handling
    
    func testErrorHandlingForInvalidFile() async throws {
        // Given: Invalid audio file URL
        let invalidURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("nonexistent.mp3")
        
        // When/Then: Should handle error gracefully
        do {
            try await audioPlayer.play(url: invalidURL)
            XCTFail("Should throw error for invalid file")
        } catch {
            XCTAssertNotNil(error)
            XCTAssertEqual(audioPlayer.state, SwiftAudioPlayerState.error(error))
            XCTAssertFalse(audioPlayer.isPlaying)
        }
    }
    
    // MARK: - Helper Methods
    
    private func generateTestAudio() async throws -> URL {
        let text = "This is test audio content that will be used for playback testing."
        return try await ttsService.generateAudioFile(from: text)
    }
    
    private func createTestArticle(title: String, content: String) -> Article {
        let context = PersistenceController.preview.container.viewContext
        let article = Article(context: context)
        article.id = UUID()
        article.title = title
        article.content = content
        article.createdAt = Date()
        return article
    }
}

// MARK: - Performance Tests

extension SwiftAudioExPlaybackTests {
    
    func testLoadTimePerformance() async throws {
        // Measure time to load and start playing TTS audio
        let audioURL = try await generateTestAudio()
        
        measure {
            Task {
                try? await audioPlayer.play(url: audioURL)
            }
        }
    }
    
    func testSeekPerformance() throws {
        // Measure seek performance
        measure {
            audioPlayer.seek(to: 30.0)
        }
    }
    
    func testSpeedChangePerformance() throws {
        // Measure speed change performance
        measure {
            for speed in [0.5, 1.0, 2.0, 4.0, 8.0, 16.0, 20.0] {
                audioPlayer.setRate(Float(speed))
            }
        }
    }
}